### ISSUE TITLE
fix syntax highlighting

### ISSUE THREAD

**Issue by holygits** [cennznet/wiki#14]
github markdown could highlight `ts,typescript,js` seems like docsify can only highlight code snippets marked 'javascript'

update all the js code snippets to `javascript` (or add plugin etc.)

e.g.
<img width="850" alt="Screen Shot 2021-04-13 at 16 14 20" src="https://user-images.githubusercontent.com/5133901/114496077-4fdd3000-9c73-11eb-8d2a-a2ef8031c8bc.png">
vs.

<img width="849" alt="Screen Shot 2021-04-13 at 16 15 19" src="https://user-images.githubusercontent.com/5133901/114496154-74390c80-9c73-11eb-9288-d21c3563b75f.png">

**Comment by Amy-Centrality** [comment]
Fixed in https://github.com/cennznet/wiki/pull/15 :D
